services:
  mysql:
    container_name: 'dogs-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dogsDB'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=password123'
      - 'MYSQL_USER=justice'
    ports:
      - '3306:3306'