services:
  mysql:
    container_name: dogs-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: dogsdb
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: secret
      MYSQL_USER: justice
    ports:
      - 3308:3306
    
  mysql2:
    container_name: users-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: secret
      MYSQL_USER: justice
    ports:
      - 3307:3306
    

# allows docker to connect to a MySQL database within the program