spring:
  profiles:
    active: local
  application:
    name: dogs
  docker:
    compose:
      lifecycle-management: start-and-stop
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "${baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.MySQLDialect