spring:
  application:
    name: dogs
  docker:
    compose:
      lifecycle-management: start-and-stop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true

dogs:
  datasource:
    url: jdbc:mysql://localhost:3308/dogsdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: justice
    password: secret

users:
  datasource:
    url: jdbc:mysql://localhost:3307/usersdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: justice
    password: secret

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

hibernate:
  hbm2ddl:
    auto: update